{% set name = "fastcrud" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastcrud-{{ version }}.tar.gz
  sha256: b00706297d880b85bd8ab7b7102128a6b31eb7aa11860747b95fb664abe5507b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - sqlalchemy >=2.0.0,<3.0.0
    - pydantic >=2.0.0,<3.0.0
    - sqlalchemy-utils >=0.41.1,<0.42.0
    - fastapi >=0.100.0,<0.112.0

test:
  imports:
    - fastcrud
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/igorbenav/fastcrud
  summary: FastCRUD is a Python package for FastAPI, offering robust async CRUD operations and flexible endpoint creation utilities.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
