{% set name = "fastcrud" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastcrud-{{ version }}.tar.gz
  sha256: 066189d835cfb98a7e74728e0fa0e119f72615543bb418ff69ecc9b3711df349

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - sqlalchemy >=2.0.0,<3.0.0
    - pydantic >=2.0.0,<3.0.0
    - sqlalchemy-utils >=0.41.1,<0.42.0
    - fastapi >=0.100.0,<0.110.0

test:
  imports:
    - fastcrud
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/igorbenav/fastcrud
  summary: FastCRUD is a Python package for FastAPI, offering robust async CRUD operations and flexible endpoint creation utilities.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
